mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rateus/", include("rate.urls", namespace="rate")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/rate/urls.py
from django.urls import path
from . import views


app_name = "rate"

urlpatterns = [
    path("", views.AuthorListView.as_view(), name="author_list"),
    path("<int:author_id>", views.author_detail, name="author_detail"),
    path("<int:author_id>/<int:review_id>", views.review_detail, name="review_detail"),
    path("<int:author_id>/review", views.review_write, name="review_write"),
    path("<int:author_id>/write", views.author_write, name="author_write"),
]

mysite/rate/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse

from .services import get_filename_by, validate_avatar


class Author(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    avatar = models.ImageField(
        upload_to="uploads/%Y/%m/%d/", validators=[validate_avatar]
    )
    bio = models.TextField()
    allow_mail = models.BooleanField(
        "Allow clients to send emails to author", default=True
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=["created"])]

    def get_absolute_url(self):
        return reverse("rate:author_detail", args=[self.id])

    def get_rating(self):
        return round(
            self.reviews.all().aggregate(models.Avg("rating"))["rating__avg"], 1
        )


class Link(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="links")
    title = models.CharField(max_length=20)
    url = models.URLField()
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["title"]
        indexes = [models.Index(fields=["title"])]

    def get_icon_url(self):
        url = self.url
        if not url.find("x.com"):
            url = url.translate(["x", ""])
        return get_filename_by(url)


class Review(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="reviews")
    rating = models.IntegerField(
        validators=[MaxValueValidator(5), MinValueValidator(1)]
    )
    name = models.CharField(max_length=40)
    email = models.EmailField()
    body = models.TextField()
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=["created"])]

mysite/rate/forms.py
from django import forms
from .models import Review


class WriteReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["rating", "name", "email", "body"]


class WriteEmailForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    body = forms.CharField(max_length=10_000, widget=forms.Textarea)

mysite/rate/views.py
from django.urls import reverse
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import ListView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import send_mail
from .models import Author, Review
from .forms import WriteReviewForm, WriteEmailForm


class AuthorListView(ListView):
    model = Author
    queryset = Author.objects.filter(active=True)
    context_object_name = "authors"
    template_name = "rate/author/list.html"
    paginate_by = 3


def author_detail(request, author_id):
    author = get_object_or_404(Author, active=True, id=author_id)
    reviews = Review.objects.filter(active=True, author=author)
    reviews = Paginator(reviews, 5)

    try:
        num = request.GET.get("page", 1)
        if num == "-1":
            num = reviews.num_pages
        page_obj = reviews.page(num)
    except PageNotAnInteger:
        page_obj = reviews.page(1)
    except EmptyPage:
        page_obj = reviews.page(1)

    return render(
        request, "rate/author/detail.html", {"author": author, "reviews": page_obj}
    )


def review_detail(request, author_id, review_id):
    author = get_object_or_404(Author, id=author_id, active=True)
    review = get_object_or_404(Review, active=True, author=author, id=review_id)

    return render(request, "rate/review/detail.html", {"review": review})


def review_write(request, author_id):
    author = get_object_or_404(Author, id=author_id)

    if request.method == "POST":
        form = WriteReviewForm(request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            review.author = author
            review.save()
            return redirect(
                reverse("rate:author_detail", args=(author_id,)) + "?page=-1"
            )
    else:
        form = WriteReviewForm()
        review = None

    return render(
        request,
        "rate/review/write.html",
        {"form": form, "author": author},
    )


def author_write(request, author_id):
    author = get_object_or_404(Author, id=author_id, active=True)

    if request.method == "POST":
        form = WriteEmailForm(request.POST)

        if form.is_valid():
            title = (
                f"You've got a message from {form.cleaned_data['name'].capitalize()}"
            )
            email = form.cleaned_data["email"]
            body = f"{email} sent you a message:\n{form.cleaned_data['body']}"
            to = author.email
            send_mail(title, body, None, [to])

            return redirect(reverse("rate:author_detail", args=(author_id,)))
    else:
        form = WriteEmailForm()

    return render(
        request, "rate/author/form_write.html", {"author": author, "form": form}
    )

mysite/rate/templates/rate/author/detail.html
{% extends 'rate/base.html' %}

{% block title %}{{ author.name }}{% endblock title %}

{% block content %}
    <div class="content">
        {% include 'rate/include/header.html' with depth=2 author=author %}
        <div class="detail-row">
            <div class="profile-container">
                {% include 'rate/author/include/card.html' with author=author text='Write review' %}
            </div>
            <div class="reviews">
                {% if reviews %}
                    <h3>Rating: {{ author.get_rating }}</h3>
                {% endif%}
                {% for review in reviews %}
                    {% include 'rate/review/include.html' with review=review %}
                {% empty %}
                    <h3>No reviews yet</h3>
                {% endfor %}
            </div>
        </div>
        {% include "rate/include/footer.html" with page_obj=reviews %}
    </div>

{% endblock content %}

mysite/rate/templates/rate/author/form.html
<form class="form" method='POST'>
    {% csrf_token %}
    <form class="form" method="post">
        <div class="form__info">
            {{ form.name.as_field_group }}
            {{ form.email.as_field_group }}
        </div>
        {{ form.body.as_field_group }}
        <input type="submit" class="button-primary" value="Send email">
    </form>
</form>

mysite/rate/templates/rate/author/form_write.html
{% extends "rate/base.html" %}

{% block title %}Write review{% endblock title %}

{%block content%}
    <div class="content">
        {% include 'rate/include/header.html' with depth=3 email_form=1 author_id=author.id %}
        <div class="detail-row detail-row_form">
            {% include 'rate/author/include/card.html' with author=author text='form' %}
            {% include 'rate/author/form.html' with form=form %}
        </div>
    </div>
{% endblock %}

mysite/rate/templates/rate/author/include/card.html
{%load static %}
<div class="card">
    <div class="card__wrapperimg"><img src="{{ author.avatar.url }}" alt="{{ author.name }}" class="card__image"></div>
    <div class="card__info">
        <h3 class="card__title">{{ author.name }}</h3>
        <p class="card__text text-primary">{{ author.bio|linebreaks }}</p>
        <ul class="card__links">
            {% for link in author.links.all %}
                <li>
                    <span class="icon">
                        <img src="{% static 'images/logos/'|add:link.get_icon_url %}" alt="">
                    </span>
                    <a class='link-primary' target='_blank' href="{{ link.url }}">{{ link.title }}</a>
                </li>
            {% endfor %}
        </ul>
        <div class="card__buttons">
            {% if text != 'form' %}
                <a href="{% if not text %}{% url 'rate:author_detail' author.id %}{% else %}{% url 'rate:review_write' author.id %}{% endif %}" class="card__button button-primary">{% if not text %}More{% else %}{{ text }}{% endif %}</a>
            {% endif%}
            {% if author.allow_mail and text != 'form' %}
                <a href="{% url 'rate:author_write' author.id %}" class="card__button button-primary">Send email</a>
            {% endif %}
        </div>
    </div>
</div>

mysite/rate/templates/rate/author/list.html
{% extends 'rate/base.html' %}

{% block title %}Rateus{% endblock title %}

{% load static %}
{% block content %}
    <div class="content">
        {% include 'rate/include/header.html' with depth=1 %}
        <div class="cards">
            <div class="container">
                {% for author in authors %}
                    {% include "rate/author/include/card.html" with author=author %}
                {% empty %}
                    <h3 style="margin: 0 auto;">Empty :/</h3>
                {% endfor %}
            </div>
        </div>
        {% include "rate/include/footer.html" with page_obj=page_obj %}
    </div>
{% endblock content %}

mysite/rate/templates/rate/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/rateus.css' %}">
</head>

<body>
    {% block content %}{% endblock content %}
</body>

</html>

mysite/rate/templates/rate/include/footer.html
<footer>
    <div class="container">
        <div class="footer__row">
            <ul class="pagination">
                <li><a class='link-primary' id="previous" href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% else %}{{ page_obj.number }}{% endif %}"
                    >Previous</a></li>
                <li><a class='link-primary' id="current" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                {% if page_obj.paginator.num_pages > 1 %}
                    <li>...</li>
                    <li><a class='link-primary' id="last" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                {% endif %}
                <li><a class='link-primary' id="next" href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% else %}{{ page_obj.number }}{% endif %}">Next</a></li>
            </ul>
        </div>
    </div>
</footer>

mysite/rate/templates/rate/include/header.html
<header>
    <div class="breadcrumbs">
        <div class="container">
            <ul>
                {% if depth > 0 %}
                    <li><a href="{% url 'rate:author_list' %}">Home</a></li>
                {% endif %}
                {% if depth > 1 %}
                    <li><a href="{% url 'rate:author_detail' author_id=author.id %}">{{ author.name }}</a></li>
                {% endif %}
                {% if depth > 2 %}
                    {% if review %}
                        <li><a href="#">Review</a></li>
                    {% elif email_form %}
                        <li><a href="#">Write</a></li>
                    {% elif review_form %}
                        <li><a href="#">Write</a></li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>
    </div>
</header>

mysite/rate/templates/rate/review/detail.html
{% extends "rate/base.html" %}

{% block title %}Review{% endblock title %}

{% block content %}
    <div class="content">
        {% include 'rate/include/header.html' with depth=3 review=review author=review.author %}
        <div class="container container-large">
            {% include 'rate/review/include.html' with review=review %}
        </div>
    </div>
{% endblock content %}

mysite/rate/templates/rate/review/form.html
<form class="form" method='POST'>
    {% csrf_token %}
    <form class="form" method="post">
        <div class="form__top">
            <div class="rating_form rating">
                <input type="radio" name="rating" value='5' class="rating_form__1 rating__star">
                <input type="radio" name="rating" value='4' class="rating_form__2 rating__star">
                <input type="radio" name="rating" value='3' class="rating_form__3 rating__star">
                <input type="radio" name="rating" value='2' class="rating_form__4 rating__star">
                <input type="radio" name="rating" value='1' checked class="rating_form__5 rating__star">
            </div>
        </div>
        <div class="form__info">
            {{ form.name.as_field_group }}
            {{ form.email.as_field_group }}
        </div>
        {{ form.body.as_field_group }}
        <input type="submit" class="button-primary" value="Rate">
    </form>
</form>

mysite/rate/templates/rate/review/include.html
<div class="review reviews__review">
    <div class="review__info">
        <div class="review__left">
            <h3 class="review__title"><a class='link-primary' href="{% url 'rate:review_detail' review.author.id review.id %}">{{ review.name }}</a><span>| {{ review.created|timesince }} ago</span></h3>
        </div>
        <div class="review__rating rating">
            {% with review.rating as review_rating %}
                {% for i in ""|center:5  %}
                    <span class="rating__star{% if review_rating >= forloop.counter %} rating__star_active{% endif %}"></span>
                {% endfor %}
            {% endwith %}
        </div>
    </div>
    <div class="review__body">
        <p class="review__text text-primary">{{ review.body|linebreaks }}</p>
    </div>
</div>

mysite/rate/templates/rate/review/write.html
{% extends "rate/base.html" %}

{% block title %}Write review{% endblock title %}

{%block content%}
    <div class="content">
        {% include 'rate/include/header.html' with depth=3 review=1 author_id=author.id %}
        <div class="detail-row detail-row_form">
            {% include 'rate/author/include/card.html' with author=author text='form' %}
            {% include 'rate/review/form.html' with form=form autho=author %}
        </div>
    </div>
{% endblock %}